export const MAINNET_BOND_PROGRAM_ID = 'EfuseVF62VgpYmXroXkNww8qKCQudeHAEzczSAC7Xsir';
export const MAINNET_ACCESS_PASS_COLLECTION_ID = 'FYCPa15hAFeDJ4CUNoMjGyQAkKPmzQ93uUaTyqae8tMN';

export const DEVNET_BOND_PROGRAM_ID = 'E1UhfWQYVQP8BfNcNMuPM3j2fypxU6o8JsCkAmcSy1Ui';
export const DEVNET_ACCESS_PASS_COLLECTION_ID = 'H7HAVkjcxNYcSDF8r2R43AypAobMGbZ5x9SYkyv8pqxk';
